language: python
python:
  - "2.7"
addons:
  postgresql: "9.3"
env: SQLA_CONN="postgresql://:@/cfdm_test"
before_script:
  - psql -c 'create database cfdm_test;' -U postgres
  - md5sum data/cfdm_test.pgdump.sql
  - psql -f data/cfdm_test.pgdump.sql -U postgres cfdm_test
  - psql -c "SELECT count(*) FROM dimcand" -U postgres cfdm_test
  - psql -f data/sql_updates/create_candidates_vw.sql -U postgres cfdm_test
  - psql -f data/sql_updates/create_candidate_detail_vw.sql -U postgres cfdm_test
  - psql -f data/sql_updates/create_committees_vw.sql -U postgres cfdm_test
  - psql -f data/sql_updates/create_totals_pacs_parties_view.sql -U postgres cfdm_test
  - psql -f data/sql_updates/create_totals_presidential_view.sql -U postgres cfdm_test
  - psql -f data/sql_updates/create_totals_house_senate_view.sql -U postgres cfdm_test
  - psql -f data/sql_updates/create_committee_detail_vw.sql -U postgres cfdm_test
  - psql -f data/sql_updates/create_linkage_names_vw.sql -U postgres cfdm_test
  - pip install -r requirements.txt
script: nosetests
